changelog:
  exclude:
    labels:
      - 'rn: test(anta)'
      - 'rn: ci(anta)'
      - 'rn: test(anta.tests)'
      - 'rn: ci(anta.tests)'
      - 'rn: test(anta.cli)'
      - 'rn: ci(anta.cli)'
      - 'rn: test(anta|anta.tests)'
      - 'rn: ci(anta|anta.tests)'
      - 'rn: test(anta|anta.cli)'
      - 'rn: ci(anta|anta.cli)'
      - 'rn: test(anta.tests|anta)'
      - 'rn: ci(anta.tests|anta)'
      - 'rn: test(anta.tests|anta.cli)'
      - 'rn: ci(anta.tests|anta.cli)'
      - 'rn: test(anta.cli|anta)'
      - 'rn: ci(anta.cli|anta)'
      - 'rn: test(anta.cli|anta.tests)'
      - 'rn: ci(anta.cli|anta.tests)'
      - 'rn: test(anta|anta.tests|anta.cli)'
      - 'rn: ci(anta|anta.tests|anta.cli)'
      - 'rn: test(anta|anta.cli|anta.tests)'
      - 'rn: ci(anta|anta.cli|anta.tests)'
      - 'rn: test(anta.tests|anta|anta.cli)'
      - 'rn: ci(anta.tests|anta|anta.cli)'
      - 'rn: test(anta.tests|anta.cli|anta)'
      - 'rn: ci(anta.tests|anta.cli|anta)'
      - 'rn: test(anta.cli|anta|anta.tests)'
      - 'rn: ci(anta.cli|anta|anta.tests)'
      - 'rn: test(anta.cli|anta.tests|anta)'
      - 'rn: ci(anta.cli|anta.tests|anta)'
      - 'rn: test'
      - 'rn: ci'
  categories:
    - title: Breaking Changes
      labels:
        - 'rn: feat(anta)!'
        - 'rn: feat(anta.tests)!'
        - 'rn: feat(anta.cli)!'
        - 'rn: feat(anta|anta.tests)!'
        - 'rn: feat(anta|anta.cli)!'
        - 'rn: feat(anta.tests|anta)!'
        - 'rn: feat(anta.tests|anta.cli)!'
        - 'rn: feat(anta.cli|anta)!'
        - 'rn: feat(anta.cli|anta.tests)!'
        - 'rn: feat(anta|anta.tests|anta.cli)!'
        - 'rn: feat(anta|anta.cli|anta.tests)!'
        - 'rn: feat(anta.tests|anta|anta.cli)!'
        - 'rn: feat(anta.tests|anta.cli|anta)!'
        - 'rn: feat(anta.cli|anta|anta.tests)!'
        - 'rn: feat(anta.cli|anta.tests|anta)!'
        - 'rn: fix(anta)!'
        - 'rn: fix(anta.tests)!'
        - 'rn: fix(anta.cli)!'
        - 'rn: fix(anta|anta.tests)!'
        - 'rn: fix(anta|anta.cli)!'
        - 'rn: fix(anta.tests|anta)!'
        - 'rn: fix(anta.tests|anta.cli)!'
        - 'rn: fix(anta.cli|anta)!'
        - 'rn: fix(anta.cli|anta.tests)!'
        - 'rn: fix(anta|anta.tests|anta.cli)!'
        - 'rn: fix(anta|anta.cli|anta.tests)!'
        - 'rn: fix(anta.tests|anta|anta.cli)!'
        - 'rn: fix(anta.tests|anta.cli|anta)!'
        - 'rn: fix(anta.cli|anta|anta.tests)!'
        - 'rn: fix(anta.cli|anta.tests|anta)!'
        - 'rn: cut(anta)!'
        - 'rn: cut(anta.tests)!'
        - 'rn: cut(anta.cli)!'
        - 'rn: cut(anta|anta.tests)!'
        - 'rn: cut(anta|anta.cli)!'
        - 'rn: cut(anta.tests|anta)!'
        - 'rn: cut(anta.tests|anta.cli)!'
        - 'rn: cut(anta.cli|anta)!'
        - 'rn: cut(anta.cli|anta.tests)!'
        - 'rn: cut(anta|anta.tests|anta.cli)!'
        - 'rn: cut(anta|anta.cli|anta.tests)!'
        - 'rn: cut(anta.tests|anta|anta.cli)!'
        - 'rn: cut(anta.tests|anta.cli|anta)!'
        - 'rn: cut(anta.cli|anta|anta.tests)!'
        - 'rn: cut(anta.cli|anta.tests|anta)!'
        - 'rn: revert(anta)!'
        - 'rn: revert(anta.tests)!'
        - 'rn: revert(anta.cli)!'
        - 'rn: revert(anta|anta.tests)!'
        - 'rn: revert(anta|anta.cli)!'
        - 'rn: revert(anta.tests|anta)!'
        - 'rn: revert(anta.tests|anta.cli)!'
        - 'rn: revert(anta.cli|anta)!'
        - 'rn: revert(anta.cli|anta.tests)!'
        - 'rn: revert(anta|anta.tests|anta.cli)!'
        - 'rn: revert(anta|anta.cli|anta.tests)!'
        - 'rn: revert(anta.tests|anta|anta.cli)!'
        - 'rn: revert(anta.tests|anta.cli|anta)!'
        - 'rn: revert(anta.cli|anta|anta.tests)!'
        - 'rn: revert(anta.cli|anta.tests|anta)!'
        - 'rn: refactor(anta)!'
        - 'rn: refactor(anta.tests)!'
        - 'rn: refactor(anta.cli)!'
        - 'rn: refactor(anta|anta.tests)!'
        - 'rn: refactor(anta|anta.cli)!'
        - 'rn: refactor(anta.tests|anta)!'
        - 'rn: refactor(anta.tests|anta.cli)!'
        - 'rn: refactor(anta.cli|anta)!'
        - 'rn: refactor(anta.cli|anta.tests)!'
        - 'rn: refactor(anta|anta.tests|anta.cli)!'
        - 'rn: refactor(anta|anta.cli|anta.tests)!'
        - 'rn: refactor(anta.tests|anta|anta.cli)!'
        - 'rn: refactor(anta.tests|anta.cli|anta)!'
        - 'rn: refactor(anta.cli|anta|anta.tests)!'
        - 'rn: refactor(anta.cli|anta.tests|anta)!'
        - 'rn: bump(anta)!'
        - 'rn: bump(anta.tests)!'
        - 'rn: bump(anta.cli)!'
        - 'rn: bump(anta|anta.tests)!'
        - 'rn: bump(anta|anta.cli)!'
        - 'rn: bump(anta.tests|anta)!'
        - 'rn: bump(anta.tests|anta.cli)!'
        - 'rn: bump(anta.cli|anta)!'
        - 'rn: bump(anta.cli|anta.tests)!'
        - 'rn: bump(anta|anta.tests|anta.cli)!'
        - 'rn: bump(anta|anta.cli|anta.tests)!'
        - 'rn: bump(anta.tests|anta|anta.cli)!'
        - 'rn: bump(anta.tests|anta.cli|anta)!'
        - 'rn: bump(anta.cli|anta|anta.tests)!'
        - 'rn: bump(anta.cli|anta.tests|anta)!'
        - 'rn: feat!'
        - 'rn: fix!'
        - 'rn: cut!'
        - 'rn: revert!'
        - 'rn: refactor!'
        - 'rn: bump!'
    - title: New features and enhancements
      labels:
        - 'rn: feat(anta)'
        - 'rn: feat(anta.tests)'
        - 'rn: feat(anta.cli)'
        - 'rn: feat(anta|anta.tests)'
        - 'rn: feat(anta|anta.cli)'
        - 'rn: feat(anta.tests|anta)'
        - 'rn: feat(anta.tests|anta.cli)'
        - 'rn: feat(anta.cli|anta)'
        - 'rn: feat(anta.cli|anta.tests)'
        - 'rn: feat(anta|anta.tests|anta.cli)'
        - 'rn: feat(anta|anta.cli|anta.tests)'
        - 'rn: feat(anta.tests|anta|anta.cli)'
        - 'rn: feat(anta.tests|anta.cli|anta)'
        - 'rn: feat(anta.cli|anta|anta.tests)'
        - 'rn: feat(anta.cli|anta.tests|anta)'
        - 'rn: feat'
    - title: Fixed issues
      labels:
        - 'rn: fix(anta)'
        - 'rn: fix(anta.tests)'
        - 'rn: fix(anta.cli)'
        - 'rn: fix(anta|anta.tests)'
        - 'rn: fix(anta|anta.cli)'
        - 'rn: fix(anta.tests|anta)'
        - 'rn: fix(anta.tests|anta.cli)'
        - 'rn: fix(anta.cli|anta)'
        - 'rn: fix(anta.cli|anta.tests)'
        - 'rn: fix(anta|anta.tests|anta.cli)'
        - 'rn: fix(anta|anta.cli|anta.tests)'
        - 'rn: fix(anta.tests|anta|anta.cli)'
        - 'rn: fix(anta.tests|anta.cli|anta)'
        - 'rn: fix(anta.cli|anta|anta.tests)'
        - 'rn: fix(anta.cli|anta.tests|anta)'
        - 'rn: fix'
    - title: Documentation
      labels:
        - 'rn: doc(anta)'
        - 'rn: doc(anta.tests)'
        - 'rn: doc(anta.cli)'
        - 'rn: doc(anta|anta.tests)'
        - 'rn: doc(anta|anta.cli)'
        - 'rn: doc(anta.tests|anta)'
        - 'rn: doc(anta.tests|anta.cli)'
        - 'rn: doc(anta.cli|anta)'
        - 'rn: doc(anta.cli|anta.tests)'
        - 'rn: doc(anta|anta.tests|anta.cli)'
        - 'rn: doc(anta|anta.cli|anta.tests)'
        - 'rn: doc(anta.tests|anta|anta.cli)'
        - 'rn: doc(anta.tests|anta.cli|anta)'
        - 'rn: doc(anta.cli|anta|anta.tests)'
        - 'rn: doc(anta.cli|anta.tests|anta)'
        - 'rn: doc'
    - title: Other Changes
      labels:
        - '*'
