# Copyright (c) 2023 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
"""
Word models management
"""

import datetime
from pydantic import BaseModel, field_validator
from typing import Any, Dict, List, Optional

from docx.shared import RGBColor


class TextItems(BaseModel):
    intro: str = f"Report generated by ANTA\nDate: {datetime.datetime.now().strftime('%Y-%m-%d at %I:%M')}"
    abstract: str = f"This is a NRFU report generated by ANTA for customer $$CUSTOMER_NAME$$ on {datetime.datetime.now().strftime('%Y-%m-%d at %I:%M')}"
    tests_description_overview: str = "TBC"
    tests_per_device_overview: str = "This section provides a list of all tests sorted by device name."
    tests_summary_by_tests: str = "This section gives an overview of result grouped by Tests name"


class Color(BaseModel):
    """Color definition object."""

    hex: str

    def rgb(self) -> RGBColor:
        """Convert color frm HEX to RGB."""
        return RGBColor(*[int(self.hex.lstrip("#")[i : i + 2], 16) for i in (0, 2, 4)])


class Colors(BaseModel):
    """
    Color style definition.

    Link: https://htmlcolorcodes.com/
    """

    headers_table: Color = Color(hex="#1F618D")
    success: Color = Color(hex="#A9DFBF")
    failure: Color = Color(hex="#F5B7B1")
    error: Color = Color(hex="#E74C3C")
    skipped: Color = Color(hex="#EB984E")


class DocxStyle(BaseModel):
    """DOCX style defnition."""

    colors: Colors = Colors()
    font_colors: Colors = Colors(headers_table=Color(hex="#FFFFFF"))
    font_size_default: int = 9
    font_name: str = "Arial"
    table_style: str = "Table Grid"
    shade_errors: bool = False
    shade_success: bool = False
    shade_failure: bool = False


SUPPORTED_FEATURES = ["tests_description", "summary_per_test", "tests_per_device"]


class TextCover(BaseModel):
    title: str = "Network Ready for Use Report"
    subtitles: List[str] = [
        f"Generated by ANTA framework on {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}",
        """Sunt aliquip fugiat sit aliqua pariatur. Laboris qui eu ex minim cupidatat nulla ea consectetur consequat aute deserunt cupidatat.
Ullamco cupidatat eiusmod ut nisi id Lorem ad do voluptate. Quis laboris irure magna veniam tempor exercitation.
    """,
    ]


class TextSection(BaseModel):
    index: int
    header: str
    description: List[str] = [
        """
Pariatur veniam ad cupidatat magna velit proident incididunt nulla tempor. Magna irure sunt laborum cupidatat eu
voluptate magna ipsum non commodo exercitation cillum sunt ullamco. Ea ea consectetur incididunt officia cillum ad
laboris veniam non anim est. Consequat aliquip pariatur ullamco elit ad.

Ex quis exercitation cupidatat nostrud ut sit mollit velit do est dolor irure. Amet voluptate magna est occaecat
aliquip ex laboris velit. Consectetur veniam tempor est non laborum magna ullamco ex.
    """
    ]
    insert: Optional[str] = None
    break_after: bool = False

    @classmethod
    @field_validator("insert")
    def supported_options(cls, v: str) -> str:
        if v in SUPPORTED_FEATURES:
            raise ValueError(f"Not a supported data to insert: {v} not in {SUPPORTED_FEATURES}")
        return v


class TextInputs(BaseModel):
    cover: TextCover
    content: List[TextSection]
