---
# .codecov.yml
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.5%
        paths:
          - "anta/"
          - "asynceapi/"
    patch:
      default:
        target: 80%
        threshold: 0%

comment:
  layout: "reach,diff,components,files"
  behavior: default
  require_changes: true

component_management:
  individual_components:
    - component_id: cli
      name: CLI
      paths:
        - "anta/cli/**"
    - component_id: asynceapi
      name: asynceapi
      paths:
        - "asynceapi/**"
    - component_id: anta_core
      name: ANTA Core
      paths:
        - "anta/**"
        - "!anta/cli/**"
        - "!anta/tests/**"
        - "!anta/input_models/**"
    - component_id: anta_tests
      name: ANTA Tests
      paths:
        - "anta/tests/**"
        - "anta/input_models/**"

ignore:
  - "tests/**/*"
  - "docs/**/*"
