################################
# Tox
################################
requires = ["tox>=4.61.4,<5.0.0", "tox-uv-bare>=1.36.0,<2.0.0"]
env_list = [
  "clean",
  "lint",
  "type",
  "py310",
  "py311",
  "py312",
  "py313",
  "py314",
  "report",
]

[env_run_base]
runner = "uv-venv-lock-runner"
description = "Run pytest with {basepython}"
extras = ["cli"]
dependency_groups = ["test"]
# posargs allows running a specific test with `tox -e <env> -- path/to/test::test`.
commands = [["pytest", { replace = "posargs", extend = true }]]
# Required to test on non-POSIX systems.
passenv = ["USERNAME"]
# A tox release changed the detected terminal width and broke snapshot tests.
set_env = { COLUMNS = "165" }

[env.lint]
description = "Check the code style"
dependency_groups = ["lint", "test", "benchmark"]
commands = [
  ["ruff", "check", "."],
  ["ruff", "format", ".", "--check"],
  ["pylint", "anta"],
  ["pylint", "tests"],
  ["pylint", "asynceapi"],
]

[env.type]
description = "Check typing"
dependency_groups = ["lint", "test", "benchmark"]
commands = [
  ["pyright", "anta"],
  ["pyright", "tests"],
  ["pyright", "asynceapi"],
]

[env.clean]
description = "Erase previous coverage reports"
package = "skip"
dependency_groups = ["test"]
commands = [["coverage", "erase"]]

[env.report]
description = "Generate coverage reports"
package = "skip"
dependency_groups = ["test"]
commands = [
  ["coverage", "--version"],
  ["coverage", "html", "--rcfile=pyproject.toml"],
  ["coverage", "xml", "--rcfile=pyproject.toml"],
]
depends = ["py311"]
