---
name: Run benchmarks
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  benchmarks:
    name: Benchmark ANTA for Python 3.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install . --group dev
      - name: Run benchmarks
        uses: CodSpeedHQ/action@63f3e98b61959fe67f146a3ff022e4136fe9bb9c # v4.17.6
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: simulation
          run: pytest --codspeed --no-cov --log-cli-level INFO tests/benchmark
