---
name: Run benchmarks
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    name: Benchmark ANTA for Python 3.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install . --group dev
      - name: Run benchmarks
        uses: CodSpeedHQ/action@a4a36bb07c0638b0b4ca52bf1f3dad1b4289e52f # v4.18.1
        with:
          mode: simulation
          run: pytest --codspeed --no-cov --log-cli-level INFO tests/benchmark
