---
name: Run benchmarks
on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  benchmarks:
    name: Benchmark ANTA for Python 3.12
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: pip install . --group dev
      - name: Run benchmarks
        uses: CodSpeedHQ/action@5582c74f32340226553e190976c937352ccca6bd # v4.2.0
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          mode: instrumentation
          run: pytest --codspeed --no-cov --log-cli-level INFO tests/benchmark
