---
# This is deploying the latest commits on main to main documentation
name: Zensical
on:
  push:
    branches:
      - main
    paths:
      # Run only if any of the following paths are changed when pushing to main
      - "docs/**"
      - "mkdocs.yml"
      - "anta/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  'build_latest_doc':
    name: 'Update Public main documentation'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: 'Setup Python 3 on runner'
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: '3.x'

      - name: Setup Git config
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: 'Build Zensical content and deploy to gh-pages to main'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            git remote set-url origin "https://x-access-token:${GH_TOKEN}@github.com/${GITHUB_REPOSITORY}.git"
            pip install --group doc -e .github/zensical_extensions
            mike deploy --push main
